### PR TITLE
Update james project SHA-1

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
Ok yeah same as last time....

**Comment by chibenwa** [comment]
Can we fix the build timely without waiting for Quan merge?

**Comment by Arsnael** [comment]
If you extract what is needed I guess...

**Comment by chibenwa** [comment]
Let's fix it here then!

**Comment by Arsnael** [comment]
We can... I'm not sure there is gonna be much left of Quan's PR though. Feels a bit odd sometimes with some merges between the two projects TBH

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
```
DistributedImapAndSmtpTest>DeploymentValidation.validateDeploymentWithMailsFromSmtp:93 » SMTPSending
```

Now the senders needs to authenticate!

Let me fix it...

**Comment by chibenwa** [comment]
This needs to be fixed on James server side.

**Comment by Arsnael** [comment]
```
[ERROR] validateDeploymentWithMailsFromSmtp  Time elapsed: 57.047 s  <<< ERROR!
org.apache.james.utils.SMTPSendingException: 
Error upon step RCPT: 530 5.7.1 Authentication Required
```

**Comment by chibenwa** [comment]
I merged it on james-project, we can now re-update the SHA-1 to latest master.

**Pull request merged**
