### PR TITLE
Adapt Jenkinsfile for PR builds on CI

### PR DESCRIPTION
**Pull request by Arsnael**
Don't merge, I test PR builds with the CI here

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
retest

**Comment by Arsnael** [comment]
test this please

**Review by LanKhuat — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]

**Pull request merged**
